name: Build and Deploy Helm Charts

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0

      - name: Package Helm charts
        run: |
          mkdir -p ./charts-packages
          for chart in $(find . -name "Chart.yaml" -exec dirname {} \;); do
            helm package $chart -d ./charts-packages
          done

      - name: Set up gh-pages branch
        run: |
          git fetch origin
          git checkout --orphan gh-pages || git checkout gh-pages
          mkdir -p gh-pages

      - name: Move Helm chart packages to gh-pages
        run: |
          for chart in ./charts-packages/*.tgz; do
            chart_name=$(basename $chart)
            chart_folder="gh-pages/$(basename $chart .tgz)"
            mkdir -p $chart_folder
            mv $chart $chart_folder/
          done

      - name: Generate Helm repository index
        run: |
          cd gh-pages
          helm repo index . --url https://<your-username>.github.io/<your-repo>

      - name: Commit and push to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploy new Helm charts"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
